-- ═══════════════════════════════════════════════════════════════════
-- Phase E — 감사 로그 + 리포트 롤업
-- 실행 환경: DAOL 사내 MariaDB (INV 스키마)
-- ═══════════════════════════════════════════════════════════════════

-- CCS_AUDIT_LOG: 관리자 감사 로그
CREATE TABLE IF NOT EXISTS INV.CCS_AUDIT_LOG (
  AUDIT_ID    VARCHAR(40)   NOT NULL,
  PROP_CD     VARCHAR(10)   NOT NULL,
  CMPX_CD     VARCHAR(10)   NULL,
  ACTOR_ID    VARCHAR(40)   NULL,
  ACTOR_TYPE  VARCHAR(10)   NOT NULL COMMENT 'GUEST|STAFF|ADMIN|SYSTEM',
  ACTION      VARCHAR(20)   NOT NULL COMMENT 'CREATE|UPDATE|DELETE|STATUS_CHANGE|LOGIN|LOGOUT',
  DOMAIN      VARCHAR(20)   NOT NULL COMMENT 'TASK|LOSTFOUND|VOC|RENTAL|DUTY|FEATURE',
  ENTITY_ID   VARCHAR(40)   NULL,
  BEFORE_JSON VARCHAR(4000) NULL,
  AFTER_JSON  VARCHAR(4000) NULL,
  CREATED_AT  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (AUDIT_ID),
  KEY IDX_AUDIT_DOMAIN (PROP_CD, DOMAIN, CREATED_AT),
  KEY IDX_AUDIT_ACTOR (ACTOR_ID, CREATED_AT)
) COMMENT='CCS 감사 로그 (모든 도메인 변경 추적)';

-- CCS_REPORT_DAILY: 일일 리포트 롤업 (미래 스케쥴드 잡 대상, 현재는 ad-hoc GROUP BY 로 대체)
CREATE TABLE IF NOT EXISTS INV.CCS_REPORT_DAILY (
  DATE_YMD       DATE          NOT NULL,
  PROP_CD        VARCHAR(10)   NOT NULL,
  CMPX_CD        VARCHAR(10)   NOT NULL,
  DEPT_CD        VARCHAR(10)   NOT NULL,
  SOURCE_TYPE    VARCHAR(20)   NOT NULL,
  REQUEST_COUNT  INT           NOT NULL DEFAULT 0,
  SLA_MET_COUNT  INT           NOT NULL DEFAULT 0,
  AVG_ELAPSED_MIN DECIMAL(10,2) NULL,
  UNIQUE_GUESTS  INT           NOT NULL DEFAULT 0,
  PRIMARY KEY (DATE_YMD, PROP_CD, CMPX_CD, DEPT_CD, SOURCE_TYPE)
) COMMENT='CCS 일일 집계 롤업 테이블 (batch 작업으로 populate 예정)';
