-- ═══════════════════════════════════════════════════════════════════
-- Phase B — 분실물(Lost&Found) + 고객불만(VOC)
-- 실행 환경: DAOL 사내 MariaDB (INV 스키마)
-- 실행 주체: DB 관리자 (서버 프로세스에서 자동 실행 안 함)
-- ═══════════════════════════════════════════════════════════════════

-- CCS_LOSTFOUND: 분실물 신고/매칭
CREATE TABLE IF NOT EXISTS INV.CCS_LOSTFOUND (
  LF_ID         VARCHAR(40)   NOT NULL COMMENT '분실물 PK (UUID)',
  PROP_CD       VARCHAR(10)   NOT NULL,
  CMPX_CD       VARCHAR(10)   NOT NULL,
  REPORTER_TYPE VARCHAR(10)   NOT NULL COMMENT 'GUEST|STAFF',
  REPORTER_REF  VARCHAR(40)   NULL COMMENT 'guest RSV_NO or staff USER_ID',
  RM_NO         VARCHAR(20)   NULL,
  CATEGORY      VARCHAR(20)   NOT NULL COMMENT 'WALLET|PHONE|CLOTHING|ACCESSORY|DOCUMENT|ETC',
  ITEM_NAME     VARCHAR(120)  NOT NULL,
  DESCRIPTION   VARCHAR(500)  NULL,
  LOCATION_HINT VARCHAR(200)  NULL COMMENT '게스트가 말한 위치 (예: 702호 침대 옆)',
  FOUND_AT      DATETIME      NULL COMMENT 'STAFF 발견 시각',
  MATCHED_LF_ID VARCHAR(40)   NULL COMMENT '매칭된 발견물 LF_ID (REPORTER_TYPE=GUEST 분실신고와 STAFF 습득의 연결)',
  STATUS_CD     VARCHAR(10)   NOT NULL DEFAULT 'REPORTED' COMMENT 'REPORTED|FOUND|MATCHED|RETURNED|DISPOSED',
  HANDLER_ID    VARCHAR(40)   NULL,
  NOTE          VARCHAR(500)  NULL,
  CREATED_AT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (LF_ID),
  KEY IDX_LF_PROP (PROP_CD, CMPX_CD, STATUS_CD),
  KEY IDX_LF_CATEGORY (CATEGORY, STATUS_CD)
) COMMENT='CCS 분실물 센터 (자체 소유, PMS_LOSTFOUND는 어댑터로 동기화)';

-- CCS_VOC: 고객 불만/피드백
CREATE TABLE IF NOT EXISTS INV.CCS_VOC (
  VOC_ID       VARCHAR(40)   NOT NULL,
  PROP_CD      VARCHAR(10)   NOT NULL,
  CMPX_CD      VARCHAR(10)   NOT NULL,
  RSV_NO       VARCHAR(40)   NULL,
  RM_NO        VARCHAR(20)   NULL,
  CATEGORY     VARCHAR(20)   NOT NULL COMMENT 'FACILITY|CLEAN|SERVICE|NOISE|BILLING|ETC',
  SEVERITY     VARCHAR(10)   NOT NULL DEFAULT 'NORMAL' COMMENT 'LOW|NORMAL|HIGH|URGENT',
  TITLE        VARCHAR(200)  NOT NULL,
  CONTENT      VARCHAR(2000) NOT NULL,
  STATUS_CD    VARCHAR(10)   NOT NULL DEFAULT 'OPEN' COMMENT 'OPEN|IN_PROG|RESOLVED|CLOSED',
  HANDLER_ID   VARCHAR(40)   NULL,
  RESOLUTION   VARCHAR(2000) NULL,
  SATISFACTION SMALLINT      NULL COMMENT '1~5, 해결 후 게스트 평가',
  CREATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  RESOLVED_AT  DATETIME      NULL,
  PRIMARY KEY (VOC_ID),
  KEY IDX_VOC_PROP (PROP_CD, CMPX_CD, STATUS_CD),
  KEY IDX_VOC_CATEGORY (CATEGORY, SEVERITY)
) COMMENT='CCS 고객 불만 관리';
