-- ═══════════════════════════════════════════════════════════════════
-- Phase D — 대여(Rental) + 당직 로그(DutyLog)
-- 실행 환경: DAOL 사내 MariaDB (INV 스키마)
-- ═══════════════════════════════════════════════════════════════════

-- CCS_RENTAL_ITEM: 대여 물품 카탈로그
CREATE TABLE IF NOT EXISTS INV.CCS_RENTAL_ITEM (
  ITEM_ID         VARCHAR(40)   NOT NULL,
  PROP_CD         VARCHAR(10)   NOT NULL,
  CMPX_CD         VARCHAR(10)   NOT NULL,
  NAME            VARCHAR(120)  NOT NULL,
  DESCRIPTION     VARCHAR(500)  NULL,
  CATEGORY        VARCHAR(20)   NOT NULL COMMENT 'UMBRELLA|CHARGER|ADAPTER|IRON|ETC',
  STOCK_TOTAL     INT           NOT NULL DEFAULT 0,
  STOCK_AVAILABLE INT           NOT NULL DEFAULT 0,
  USE_YN          CHAR(1)       NOT NULL DEFAULT 'Y',
  CREATED_AT      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ITEM_ID),
  KEY IDX_RENTAL_ITEM_PROP (PROP_CD, CMPX_CD, USE_YN)
) COMMENT='CCS 대여 물품 마스터';

-- CCS_RENTAL_ORDER: 대여 주문
CREATE TABLE IF NOT EXISTS INV.CCS_RENTAL_ORDER (
  ORDER_ID     VARCHAR(40)   NOT NULL,
  PROP_CD      VARCHAR(10)   NOT NULL,
  CMPX_CD      VARCHAR(10)   NOT NULL,
  RSV_NO       VARCHAR(40)   NULL,
  ITEM_ID      VARCHAR(40)   NOT NULL,
  QTY          INT           NOT NULL DEFAULT 1,
  STATUS_CD    VARCHAR(10)   NOT NULL DEFAULT 'REQUESTED' COMMENT 'REQUESTED|LOANED|RETURNED|LOST',
  REQUESTED_AT DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LOANED_AT    DATETIME      NULL,
  DUE_AT       DATETIME      NULL,
  RETURNED_AT  DATETIME      NULL,
  HANDLER_ID   VARCHAR(40)   NULL,
  NOTE         VARCHAR(500)  NULL,
  PRIMARY KEY (ORDER_ID),
  KEY IDX_RENTAL_ORDER_PROP (PROP_CD, CMPX_CD, STATUS_CD),
  KEY IDX_RENTAL_ORDER_RSV (RSV_NO)
) COMMENT='CCS 대여 주문/반납 이력';

-- CCS_DUTY_LOG: 당직 로그
CREATE TABLE IF NOT EXISTS INV.CCS_DUTY_LOG (
  LOG_ID            VARCHAR(40)   NOT NULL,
  PROP_CD           VARCHAR(10)   NOT NULL,
  CMPX_CD           VARCHAR(10)   NOT NULL,
  DUTY_DATE         DATE          NOT NULL,
  SHIFT_CD          VARCHAR(10)   NOT NULL COMMENT 'DAY|NIGHT',
  MANAGER_ID        VARCHAR(40)   NOT NULL,
  HANDOVER_FROM     VARCHAR(40)   NULL,
  HANDOVER_TO       VARCHAR(40)   NULL,
  SUMMARY           VARCHAR(2000) NULL,
  INCIDENTS         VARCHAR(4000) NULL,
  PMS_AUDIT_DONE_YN CHAR(1)       NOT NULL DEFAULT 'N',
  CREATED_AT        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (LOG_ID),
  KEY IDX_DUTY_DATE (PROP_CD, CMPX_CD, DUTY_DATE, SHIFT_CD)
) COMMENT='CCS 당직 로그 (교대/인수인계/사건 타임라인)';
